version: 2

sources:
  - name: as400_raw
    description: "Raw data extracted from AS400 legacy system"
    schema: main_raw
    tables:
      - name: cusmas
        description: "Customer Master file from AS400"
        columns:
          - name: customer_id
            description: "Primary key - Customer number"
            tests:
              - unique
              - not_null
          - name: customer_name
            description: "Company name"
          - name: segment
            description: "Customer segment (E=Enterprise, M=Mid, S=Small, T=Startup)"
          - name: credit_limit
            description: "Credit limit in dollars"
          - name: payment_terms
            description: "Standard payment terms in days"
          - name: account_status
            description: "A=Active, I=Inactive, C=Closed"

      - name: armas
        description: "AR Invoice Master file from AS400"
        columns:
          - name: invoice_number
            description: "Primary key - Invoice number"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Foreign key to customer"
            tests:
              - not_null
          - name: invoice_amount
            description: "Original invoice amount"
          - name: current_balance
            description: "Remaining balance"
          - name: status
            description: "OP=Open, PD=Paid, PP=Partial, DP=Disputed, WO=WriteOff"

      - name: paytran
        description: "Payment Transaction file from AS400"
        columns:
          - name: payment_id
            description: "Primary key - Payment ID"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Foreign key to customer"
          - name: payment_amount
            description: "Payment amount"
          - name: applied_flag
            description: "Y=Applied, N=Unapplied"

      - name: gljrn
        description: "GL Journal Entry file from AS400"
        columns:
          - name: journal_id
            description: "Journal entry ID"
            tests:
              - not_null
          - name: line_number
            description: "Line number within journal"
          - name: debit_amount
            description: "Debit amount"
          - name: credit_amount
            description: "Credit amount"